cats99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats99/app/models/cat.rb
require 'date'

class Cat < ApplicationRecord
  COLORS = %w(red green black white blue yellow orange)

  validates :birth_date, :color, :sex, :description, presence:true
  validates :name, uniqueness: true
  validates :color, inclusion: { in: COLORS, message: "Input is not a valid color" }
  validate  :validate_sex

  def validate_sex
    if sex.present? && !(sex == 'M' || sex == 'F')
      self.errors[:sex] << "Not a valid sex"
    end
  end

  def age
    now = Date.current
    age = now.year - birth_date.year
    age -= 1 if now.yday < birth_date.yday
    age
  end

end

cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.create(cat_params)
    redirect_to cat_url(@cat)
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: 422
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :sex, :color, :description)
  end

end

cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats99/app/views/cats/edit.html.erb
<form action="<%= cat_url(@cat) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <table>
    <thead>
      <tr>
        <th colspan="2" align="center">New Cat</th>
      </tr>
    </thead>
    <tbody>
      <tr>

        <td>Name: </td>
        <td>
          <input id="name"
          type="text"
          name="cat[name]"
          value="<%= @cat.name %>">
        </td>
      </tr>
      <tr>
        <td>Birthday: </td>
        <td><input id="birthday"
          type="date"
          name="cat[birth_date]"
          value="<%= @cat.birth_date %>">
        </td>
      </tr>
      <tr>
        <td>Color: </td>
        <td><select id="color" name="cat[color]">
          <option disabled "<% @cat.color.nil? ? 'selected' : ''%> ">Select a color</option>
          <% Cat::COLORS.each do |color| %>
          <option value="<%= color %>" "<% color==@cat.color ? 'selected' : ''%>"><%= color %></option>
          <% end %>
        </select></td>
      </td>
    </tr>
    <tr>
      <td>Sex: </td>
      <td>
        <input id="M" type="radio" name="cat[sex]" "<%= @cat.sex == 'M' ? 'checked' : '' %>">
        <label for="M">M</label>
        <input id="F" type="radio" name="cat[sex]" "<%= @cat.sex == 'F' ? 'checked' : '' %>">
        <label for="F">F</label>
      </td>
    </tr>
    <tr>
      <td>Description: </td>
      <td><textarea id="description" name="cat[description]"><%=@cat.description%></textarea>
      </td>
    </tr>
  </tbody>
  <tfoot>
    <tr>
      <td><input type="submit" value="Create Cat"></td>
    </tr>
  </tfoot>
</table>

cats99/app/views/cats/index.html.erb
<h1> All my Cats </h1>

<% @cats.each do |cat| %>
<ul>
  <li><%= cat.name %></li>
  <li><a href="<%= cat_url(cat) %>">Cat's Show</a></li>
</ul>

<% end %>

cats99/app/views/cats/new.html.erb
<form action="<%= cats_url %>" method="post">
  <!-- <input type="hidden" name="_method" value="patch"> -->
  <table>
    <thead>
      <tr>
        <th colspan="2" align="center">New Cat</th>
      </tr>
    </thead>
    <tbody>
      <tr>

        <td>Name: </td>
        <td>
          <input id="name"
          type="text"
          name="cat[name]"
          value="<%= @cat.name %>">
        </td>
      </tr>
      <tr>
        <td>Birthday: </td>
        <td><input id="birthday"
          type="date"
          name="cat[birth_date]"
          value="<%= @cat.birth_date %>">
        </td>
      </tr>
      <tr>
        <td>Color: </td>
        <td><select id="color" name="cat[color]">
          <option disabled selected>Select a color</option>
          <% Cat::COLORS.each do |color| %>
          <option value="<%= color %>"><%= color %></option>
          <% end %>
        </select></td>
      </td>
    </tr>
    <tr>
      <td>Sex: </td>
      <td><select id="sex" name="cat[sex]">
        <option disabled selected>Select a sex</option>
        <option value="M">M</option>
        <option value="F">F</option>
      </select></td>
    </tr>
    <tr>
      <td>Description: </td>
      <td><textarea id="description" name="cat[description]">
      </textarea>
    </td>
  </tr>
</tbody>
<tfoot>
  <tr>
    <td><input type="submit" value="Create Cat"></td>
  </tr>
</tfoot>
</table>

cats99/app/views/cats/show.html.erb
<table>
  <thead>
    <tr>
      <th colspan="2" align="center"><%= @cat.name %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Birthday: </td>
      <td><%= @cat.birth_date %></td>
    </tr>
    <tr>
      <td>Color: </td>
      <td><%= @cat.color %></td>
    </tr>
    <tr>
      <td>Sex: </td>
      <td><%= @cat.sex %></td>
    </tr>
    <tr>
      <td>Age: </td>
      <td><%= @cat.age %></td>
    </tr>
    <tr>
      <td>Description: </td>
      <td><%= @cat.description %></td>
    </tr>
  </tbody>
  <tfoot>
    <tr>
      <td><a href="<%= cats_url %>">Cat's Index</a></td>
    </tr>
  </tfoot>
</table>

cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>